heat_template_version: 2014-10-16

description: A template to deploy a load balanced web server

parameters:
  image:
    type: string
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini
  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: INF4410-mini
  subnet_id:
    type: string
    description: Sous-reseau dans lequel le load balancer sera situe
    default: 22207ede-1911-47ca-b509-5698e34cf46c  
  key_name:
    type: string
    default: coupal
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: reseau-pour-tous
  public_network:
    type: string
    label: Public network name or ID
    description: Network to attach instance to.
    default: INF4410-05-net
resources:
  web_nodes:
      type: OS::Heat::ResourceGroup
      properties:
        count: 2
        resource_def:
          type: OS::Nova::Server
          properties:
            flavor: { get_param: flavor }
            image: { get_param: image }
            key_name: { get_param: key_name }
            networks: 
              - network: { get_param: public_network }
              - network: { get_param: private_network }
            user_data:
              str_replace:
                template: |
                  #!/bin/bash
                  touch /tmp/test
                  wget http://secretaire.dorsal.polymtl.ca/~hdaoud/infonuagique/server.py -O /root/server.py > /tmp/wget.out 2>&1
                  python /root/server.py & > /tmp/python.out 2>&1
                params:
                  rien: dutout
  pool:
    type: OS::Neutron::Pool
    properties :
      monitors: [{get_resource: monitor}]
      subnet_id: {get_param: subnet_id}
      lb_method: ROUND_ROBIN
      protocol: HTTP
      vip:
        protocol_port: 80
  lbalancer:
      type: OS::Neutron::LoadBalancer
      properties:
        pool_id:  {get_resource: pool}
        protocol_port: 80
  monitor:
      type: OS::Neutron::HealthMonitor
      properties:
       delay: 11        
       max_retries: 2
       timeout: 8
       type: TCP
outputs:
  pool_ip_address:
    value: {get_attr: [pool, vip, address]}
    description: The IP address of the load balancing pool